### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [nainglinaung/scaper-dashboard#1]
Hello  👋 , thank you for your effort on the code submission. I am Olivier Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
Before proceeding further in the code review tomorrow, please review https://github.com/nainglinaung/scaper-dashboard/issues/2

**Comment by olivierobert** [comment]
I have now completed the first round of code reviews on both repositories. I am looking forward to your feedback on all opened issues.

**Comment by nainglinaung** [comment]
Hi Olivier, I've successfully submitted pull requests addressing the current issues. Could you please take a moment to review it?

**Comment by olivierobert** [comment]
Sure. I will proceed with the second round of reviews. If all is well then we can aim to wrap up this stage of the process today.

**Comment by olivierobert** [comment]
I have completed the review of all the PRs assigned to me. Have a check on the comments. There is now sufficient information to finalize the assessment. I will still be available to answer any further feedback from you but no more changes are expected from you at this stage. Thank you for your efforts
